//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadElec
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VentaEntities : DbContext
    {
        public VentaEntities()
            : base("name=VentaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Compra> Compra { get; set; }
        public virtual DbSet<CompraDetalle> CompraDetalle { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Venta> Venta { get; set; }
        public virtual DbSet<VentaDetalle> VentaDetalle { get; set; }
    
        public virtual ObjectResult<paClienteListar_Result> paClienteListar(string parametro)
        {
            var parametroParameter = parametro != null ?
                new ObjectParameter("parametro", parametro) :
                new ObjectParameter("parametro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paClienteListar_Result>("paClienteListar", parametroParameter);
        }
    
        public virtual ObjectResult<paEmpleadoListar_Result> paEmpleadoListar(string parametro)
        {
            var parametroParameter = parametro != null ?
                new ObjectParameter("parametro", parametro) :
                new ObjectParameter("parametro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paEmpleadoListar_Result>("paEmpleadoListar", parametroParameter);
        }
    
        public virtual ObjectResult<paProductoListar_Result> paProductoListar(string parametro)
        {
            var parametroParameter = parametro != null ?
                new ObjectParameter("parametro", parametro) :
                new ObjectParameter("parametro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paProductoListar_Result>("paProductoListar", parametroParameter);
        }
    
        public virtual ObjectResult<paProveedorListar_Result> paProveedorListar(string parametro)
        {
            var parametroParameter = parametro != null ?
                new ObjectParameter("parametro", parametro) :
                new ObjectParameter("parametro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paProveedorListar_Result>("paProveedorListar", parametroParameter);
        }
    
        public virtual ObjectResult<paUsuarioListar_Result> paUsuarioListar(string parametro)
        {
            var parametroParameter = parametro != null ?
                new ObjectParameter("parametro", parametro) :
                new ObjectParameter("parametro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paUsuarioListar_Result>("paUsuarioListar", parametroParameter);
        }
    
        public virtual ObjectResult<paCliListar_Result> paCliListar(string parametro)
        {
            var parametroParameter = parametro != null ?
                new ObjectParameter("parametro", parametro) :
                new ObjectParameter("parametro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paCliListar_Result>("paCliListar", parametroParameter);
        }
    
        public virtual ObjectResult<paEmpListar_Result> paEmpListar(string parametro)
        {
            var parametroParameter = parametro != null ?
                new ObjectParameter("parametro", parametro) :
                new ObjectParameter("parametro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paEmpListar_Result>("paEmpListar", parametroParameter);
        }
    
        public virtual ObjectResult<paProdListar_Result> paProdListar(string parametro)
        {
            var parametroParameter = parametro != null ?
                new ObjectParameter("parametro", parametro) :
                new ObjectParameter("parametro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paProdListar_Result>("paProdListar", parametroParameter);
        }
    
        public virtual ObjectResult<paProListar_Result> paProListar(string parametro)
        {
            var parametroParameter = parametro != null ?
                new ObjectParameter("parametro", parametro) :
                new ObjectParameter("parametro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paProListar_Result>("paProListar", parametroParameter);
        }
    
        public virtual ObjectResult<paUsuListar_Result> paUsuListar(string parametro)
        {
            var parametroParameter = parametro != null ?
                new ObjectParameter("parametro", parametro) :
                new ObjectParameter("parametro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paUsuListar_Result>("paUsuListar", parametroParameter);
        }
    
        public virtual ObjectResult<paProductoofListar_Result> paProductoofListar(string parametro)
        {
            var parametroParameter = parametro != null ?
                new ObjectParameter("parametro", parametro) :
                new ObjectParameter("parametro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paProductoofListar_Result>("paProductoofListar", parametroParameter);
        }
    
        public virtual ObjectResult<paPrctListar_Result> paPrctListar(string parametro)
        {
            var parametroParameter = parametro != null ?
                new ObjectParameter("parametro", parametro) :
                new ObjectParameter("parametro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paPrctListar_Result>("paPrctListar", parametroParameter);
        }
    
        public virtual ObjectResult<listarVentaDetalle_Result> listarVentaDetalle()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listarVentaDetalle_Result>("listarVentaDetalle");
        }
    
        public virtual ObjectResult<VentaDetalleListar_Result> VentaDetalleListar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VentaDetalleListar_Result>("VentaDetalleListar");
        }
    
        public virtual ObjectResult<Usuariolistar_Result> Usuariolistar(string parametro)
        {
            var parametroParameter = parametro != null ?
                new ObjectParameter("parametro", parametro) :
                new ObjectParameter("parametro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usuariolistar_Result>("Usuariolistar", parametroParameter);
        }
    
        public virtual ObjectResult<paVENTASDETALLE_Result> paVENTASDETALLE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paVENTASDETALLE_Result>("paVENTASDETALLE");
        }
    
        public virtual ObjectResult<ProductoListar_Result> ProductoListar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductoListar_Result>("ProductoListar");
        }
    
        public virtual ObjectResult<PRODUCTOLIST_Result> PRODUCTOLIST()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PRODUCTOLIST_Result>("PRODUCTOLIST");
        }
    }
}
